#ifndef CONFIG_H
#define CONFIG_H

#define WIFI_SSID "YOUR_WIFI"
#define WIFI_PASS "YOUR_PASSWORD"

#define ACCOUNT_SID "YOUR_TWILIO_SID"
#define AUTH_TOKEN "YOUR_TWILIO_AUTH_TOKEN"

#define FROM_NUMBER "+1234567890"
#define TO_NUMBER "+91XXXXXXXXXX"

#endif
